// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class groupinfo
{
    public int Id { get; set; }

    public int GId { get; set; }

    public string ItemName { get; set; }

    public string Item_Remarks { get; set; }

    public DateTime createTime { get; set; }

    public string sort { get; set; }

    public int creator { get; set; }

    public int complaint { get; set; }

    public int delete { get; set; }

    public virtual grouping GIdNavigation { get; set; }

    public virtual user creatorNavigation { get; set; }
}