// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class grouping
{
    public int Id { get; set; }

    public string ItemName { get; set; }

    public DateTime createTime { get; set; }

    public int statistics { get; set; }

    public string sort { get; set; }

    public virtual ICollection<groupinfo> groupinfos { get; set; } = new List<groupinfo>();
}