// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class user
{
    public int Id { get; set; }

    public string UID { get; set; }

    public string username { get; set; }

    public string pwd { get; set; }

    public string pwd_history { get; set; }

    public int role { get; set; }

    public int? banned { get; set; }

    public string banned_remarks { get; set; }

    public int enable { get; set; }

    public DateTime createTime { get; set; }

    public DateTime? loginTime { get; set; }

    public virtual ICollection<groupinfo> groupinfos { get; set; } = new List<groupinfo>();
}