// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity.Models;

public partial class workorder
{
    public int ItemID { get; set; }

    public int creator { get; set; }

    public string remarks { get; set; }

    public int violation { get; set; }

    public DateTime createTime { get; set; }

    public int? existence { get; set; }

    public virtual groupinfo Item { get; set; }

    public virtual user creatorNavigation { get; set; }

    public virtual user violationNavigation { get; set; }
}